---
- name: Scrape AS3 from Gold device
  hosts: "gold"
  connection: local
  vars:
    provider:
      server: "{{ hostvars[inventory_hostname].bigip_mgmt }}"
      user: admin
      password: "{{ f5adminpassword }}"
      validate_certs: false
      server_port: 443
  gather_facts: false
  any_errors_fatal: true

  tasks:

#    - name: clone git repo
#      shell: git clone git@github.com:megamattzilla/concord-as3-import.git

    # - name: Scrape AS3 declaration 
    #   uri:
    #     url: "https://{{ hostvars[inventory_hostname].bigip_mgmt }}:{{ port | default('443')}}/mgmt/shared/appsvcs/declare"
    #     user: "{{ provider.user }}"
    #     password: "{{ f5adminpassword }}"
    #     validate_certs: false
    #     force_basic_auth: yes
    #     method: GET
    #     timeout: 180
    #     return_content: yes
    #     status_code: 200
    #   register: as3_declaration 

    - debug:
        msg: "{{ as3_declaration }}"

    - name: POST AS3 declaration to F5 VE 1
      uri:
        url: "https://192.168.116.5:{{ port | default('443')}}/mgmt/shared/appsvcs/declare"
        user: "{{ provider.user }}"
        password: "{{ f5adminpassword }}"
        validate_certs: false
        force_basic_auth: yes
        method: POST
        timeout: 180
        body_format: json
        body: "{{ as3_declaration  }}"
        return_content: yes
        status_code: [ 200, 202]
      register: as3id

    - name: Get task status for as3 patch
      uri:
        url: "https://192.168.116.5:{{ port | default('443')}}/mgmt/shared/appsvcs/task/{{ as3id.json.id }}"
        user: "{{ provider.user }}"
        password: "{{ f5adminpassword }}"
        validate_certs: false
        force_basic_auth: yes
        method: GET
        return_content: yes
        status_code: 200
      register: patchtaskstatus
      until: patchtaskstatus.json.results[0].message == 'success'
      retries: 60 # retry X times  
      delay: 2 # pause for X sec b/w each call
      when:  as3id.status == 202